apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

namePrefix: dev-

images:
  - name: fcj-multistage
    newName: 145023123305.dkr.ecr.us-east-1.amazonaws.com/fcj-multistage
    newTag: latest

patches:
  - path: patch.yaml
    target:
      kind: Deployment
      name: multistage-app
