apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

namePrefix: dev-

<<<<<<< HEAD
=======
images:
  - name: fcj-chatbot
    newName: 145023123305.dkr.ecr.us-east-1.amazonaws.com/fcj-chatbot
    newTag: latest

>>>>>>> parent of 3f3fd6e (Create file yaml for deploy 2 projects)
patches:
  - path: patch-chatbot.yaml
    target:
      kind: Deployment
      name: chatbot-app

images:
  - name: chatbot
    newName: 145023123305.dkr.ecr.us-east-1.amazonaws.com/fcj-chatbot
    newTag: 1f9b8cafe4018f436a53eeca019de04c8306e37f

