apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

namePrefix: dev-

images:
  - name: fcj-chatbot
    newName: 145023123305.dkr.ecr.us-east-1.amazonaws.com/fcj-chatbot
    newTag: latest
  - name: project2-web
    newName: 145023123305.dkr.ecr.us-east-1.amazonaws.com/project2-web
    newTag: latest

patches:
  - path: patch.yaml
