apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

namePrefix: dev-

images:
- name: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/chatbot-app
  newTag: latest

patches:
- path: patch.yaml
