apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment-combined.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- pvc.yaml

namespace: default

commonLabels:
  app.kubernetes.io/name: chatbot-app
  app.kubernetes.io/managed-by: kustomize
